version: '3'

services:
  load_balancer:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      private_network:
        ipv4_address: 10.0.0.10 
    depends_on:
      - web_server1
      - web_server2
      
  web_server1:
    build:
      context: ./app_server1
    networks:
      private_network:
        ipv4_address: 10.0.0.11  

  web_server2:
    build:
      context: ./app_server2
    networks:
      private_network:
        ipv4_address: 10.0.0.12

networks:
  private_network:
    ipam:
      config:
        - subnet: 10.0.0.0/24
          gateway: 10.0.0.1
